# Generated by Django 4.2.23 on 2025-11-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedata',
            name='attn_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
