# Generated by Django 4.2.23 on 2025-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_attendancedata_attn_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
