# Generated by Django 4.2.23 on 2025-11-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_bridgetokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgetokens',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
